ARG PROJECT_NAME=personal-blog
ARG PROJECT_PATH=/opt/$PROJECT_NAME
ARG APP_NAME=app
ARG APP_PATH=/opt/$PROJECT_NAME/$APP_NAME
ARG POETRY_HOME=/opt/poetry
ARG POETRY_CACHE_DIR=/opt/.cache
ARG PYTHON_VERSION=3.12
ARG POETRY_VERSION=1.7.1

# Stage: staging
FROM python:$PYTHON_VERSION
ARG PROJECT_NAME
ARG PROJECT_PATH
ARG APP_NAME
ARG APP_PATH
ARG POETRY_VERSION
ARG POETRY_HOME
ARG POETRY_CACHE_DIR

ENV \
    PYTHONPATH=$PROJECT_PATH \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONFAULTHANDLER=1
ENV \
    POETRY_VERSION=$POETRY_VERSION \
    POETRY_HOME=$POETRY_HOME \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_VIRTUALENVS_CREATE=true \
    POETRY_NO_INTERACTION=1 \
    POETRY_CACHE_DIR=$POETRY_CACHE_DIR

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH=$POETRY_HOME/bin:$PATH

# Import our project files
WORKDIR $PROJECT_PATH
COPY ./poetry.lock ./pyproject.toml ./
COPY ./ ./

# Install project
RUN poetry install --without dev && rm -rf $POETRY_CACHE_DIR

WORKDIR $APP_PATH
