version: '3.8'

volumes:
  postgres_data:

networks:
  blog_net:

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    restart: always
    ports:
      - '8000:8000'
    networks:
      - blog_net
    env_file:
      - ./app/env/.env.dev
    volumes:
      - ./app:/opt/personal-blog/app
      - ./app/static:/opt/personal-blog/app/static
      - ./app/media:/opt/personal-blog/app/media
    depends_on:
      - postgres
    command: sh -c 'poetry run python manage.py collectstatic --no-input &&
                    poetry run python manage.py makemigrations &&
                    poetry run python manage.py migrate &&
                    poetry run python manage.py runserver 0.0.0.0:8000'

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    env_file:
      - ./app/env/.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - blog_net

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - '80:80'
    networks:
      - blog_net
    volumes:
      - ./app/static:/opt/personal-blog/app/static
      - ./app/media:/opt/personal-blog/app/media
      - ./docker/nginx/dev/:/etc/nginx/conf.d:ro
    links:
      - django
    depends_on:
      - django
